version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fastapi-admin
    healthcheck:
      test: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
  api:
    build: .
    restart: always
    environment:
      DATABASE_URL: mysql://root:123456@mysql:3306/fastapi-admin
    ports:
      - '8000:8000'
    depends_on:
      - mysql
    image: prismspay
    command: uvicorn examples.main:app --port 8000 --host 0.0.0.0
