site_name: FastAPI Admin
site_url: https://github.com/fastapi-admin/fastapi-admin
repo_url: https://github.com/fastapi-admin/fastapi-admin
site_description: A fast admin dashboard based on FastAPI and TortoiseORM with tabler ui, inspired by Django admin.
repo_name: fastapi-admin/fastapi-admin
site_author: long2ice
theme:
  logo: https://raw.githubusercontent.com/fastapi-admin/fastapi-admin/dev/images/icon-white.svg
  favicon: https://raw.githubusercontent.com/fastapi-admin/fastapi-admin/dev/images/favicon.png
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to default mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlight
    - navigation.top
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
nav:
  - Home: index.md
  - Getting Started:
      - getting_started/installation.md
      - getting_started/quick_start.md
  - Reference:
      - reference/index.md
      - reference/resource.md
      - Widget:
          - reference/widget/filter.md
          - reference/widget/display.md
          - reference/widget/input.md
      - reference/login.md
      - reference/file_upload.md
      - reference/middleware.md
      - reference/permission.md
      - reference/admin_log.md
      - reference/global_search.md
      - reference/errors.md
      - reference/notification.md
  - Customization:
      - custom/page.md
      - custom/overwrite.md
      - custom/widget.md
      - custom/file_upload.md
      - custom/provider.md
      - custom/action.md
  - Pro Version For Sponsor:
      - pro/sponsor.md
      - pro/exclusive.md
      - pro/installation.md
      - pro/upgrade.md
      - pro/support.md
extra:
  alternate:
    - name: English
      link: /
    - name: 简体中文
      link: /zh/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/long2ice
  analytics:
    provider: google
    property: G-VFN6RZTCH3
copyright: Copyright &copy; 2021 long2ice

plugins:
  - search
  - git-revision-date-localized:
      type: datetime
dev_addr: 127.0.0.1:7999
